server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ankitgangwar1082006/foodcourt-config-repo.git
          username: ankitgangwar1082006
          password: ${CONFIG_REPO_PAT}
          default-label: main
